export class IslandAudio{
constructor(){this.ctx=null;this.enabled=true;this.interval=null;this.paused=false;this.last={};}
async start(){if(!this.enabled)return;try{if(!this.ctx){this.ctx=new (window.AudioContext||window.webkitAudioContext)();this.master=this.ctx.createGain();this.master.gain.value=.22;this.master.connect(this.ctx.destination);this.makeWind();this.interval=setInterval(()=>{if(this.enabled&&!this.paused&&this.ctx.state==='running'){this.note([220,261.63,329.63,392,440,523.25][Math.floor(Math.random()*6)],.08,3.7,'sine');if(Math.random()>.65)this.chirp();}},3300);}await this.ctx.resume();}catch{this.enabled=false;}}
makeWind(){const n=this.ctx.sampleRate*4,b=this.ctx.createBuffer(1,n,this.ctx.sampleRate),d=b.getChannelData(0);let prev=0;for(let i=0;i<n;i++){prev=(prev+(Math.random()*2-1)*.035)/1.02;d[i]=prev;}const s=this.ctx.createBufferSource();s.buffer=b;s.loop=true;const f=this.ctx.createBiquadFilter();f.type='lowpass';f.frequency.value=450;const g=this.ctx.createGain();g.gain.value=.4;s.connect(f);f.connect(g);g.connect(this.master);s.start();}
note(freq,volume=.2,duration=.2,type='sine',endFreq=null){if(!this.ctx||!this.enabled||this.paused||this.ctx.state!=='running')return;const t=this.ctx.currentTime,o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type=type;o.frequency.setValueAtTime(freq,t);if(endFreq)o.frequency.exponentialRampToValueAtTime(endFreq,t+duration);g.gain.setValueAtTime(.001,t);g.gain.exponentialRampToValueAtTime(Math.max(.002,volume),t+.015);g.gain.exponentialRampToValueAtTime(.001,t+duration);o.connect(g);g.connect(this.master);o.start();o.stop(t+duration+.05);}
chirp(){this.note(1300,.07,.09,'sine',2400);setTimeout(()=>this.note(1800,.04,.07,'sine',2400),120);}
play(type){if(!this.ctx)return;let now=performance.now();if(now-(this.last[type]||0)<90)return;this.last[type]=now;switch(type){case'gather':this.note(170,.24,.08,'triangle',65);break;case'swing':this.note(350,.12,.11,'triangle',100);break;case'aurora-aim':this.note(920,.12,.06,'sine',460);setTimeout(()=>this.note(260,.13,.12,'triangle',90),35);break;case'hit':this.note(130,.26,.12,'triangle',48);this.note(520,.04,.13);break;case'damage':this.note(110,.35,.2,'sawtooth',55);break;case'dash':this.note(370,.1,.16,'sine',800);break;case'build':this.note(280,.18,.16,'triangle',140);setTimeout(()=>this.note(440,.1,.3),100);break;case'defeat':this.note(390,.13,.15);setTimeout(()=>this.note(590,.1,.3),90);break;case'heal':case'rest':[330,440,660].forEach((f,i)=>setTimeout(()=>this.note(f,.1,.5),i*100));break;case'shrine':case'victory':[261.63,329.63,392,523.25,659.25].forEach((f,i)=>setTimeout(()=>this.note(f,.16,1.4),i*180));break;}}
async toggle(){this.enabled=!this.enabled;if(this.enabled){await this.start();if(this.master)this.master.gain.setTargetAtTime(.22,this.ctx.currentTime,.1);}else if(this.master)this.master.gain.setTargetAtTime(0,this.ctx.currentTime,.1);return this.enabled;}
setPaused(paused){this.paused=paused;if(this.ctx){if(paused)this.ctx.suspend().catch(()=>{});else if(this.enabled)this.ctx.resume().catch(()=>{});}}
}
