export class OnlineRoom{
constructor(info,callbacks){this.info=info;this.cb=callbacks;this.host=info.hostId===info.playerId;this.connected=true;this.queue=[];this.busy=false;this.stopped=false;this.ackSeq=0;this.peers=[];this.failures=0;this.lastSuccess=Date.now();this.teleport=false;this.timer=null;}
start(){this.timer=setInterval(()=>this.sync(),400);this.sync();}
action(type,data={}){if(this.queue.length>24||!this.connected)return false;this.queue.push({id:crypto.randomUUID(),type,...data});return true;}
async sync(){if(this.busy||this.stopped||globalThis.document?.hidden)return;this.busy=true;const actions=this.queue.slice(0,8),payload={playerId:this.info.playerId,position:this.cb.position(),actions,teleport:this.teleport};if(this.host){payload.snapshot=this.cb.snapshot();payload.ackSeq=this.ackSeq;}try{const r=await fetch(`/api/rooms/${this.info.code}/sync`,{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+this.info.token},body:JSON.stringify(payload),signal:AbortSignal.timeout(7000)});const data=await r.json();if(!r.ok)throw Object.assign(new Error(data.error||'连接中断'),{fatal:r.status===401||r.status===404});this.teleport=false;const ids=new Set(actions.map(a=>a.id));this.queue=this.queue.filter(a=>!ids.has(a.id));this.peers=data.players;const host=data.hostId===this.info.playerId;if(host!==this.host){this.host=host;this.ackSeq=data.ackSeq;this.cb.role(host,data.recovery||data.snapshot);}this.connected=true;this.lastSuccess=Date.now();if(this.failures)this.cb.status('connected');this.failures=0;if(!this.host&&data.snapshot)this.cb.world(data.snapshot);if(this.host&&data.recovery)this.cb.world(data.recovery);this.cb.peers(data.players);if(this.host){for(const e of data.events){if(e.seq>this.ackSeq){this.cb.action(e);this.ackSeq=e.seq;}}}this.cb.status('connected',data.players.length);}
catch(e){this.failures++;this.connected=false;this.cb.status(e.fatal?'expired':'reconnecting',null,e.message);if(e.fatal){clearInterval(this.timer);this.timer=null;this.stopped=true;}}finally{this.busy=false;}}
async leave(){this.stopped=true;clearInterval(this.timer);try{await fetch(`/api/rooms/${this.info.code}/leave`,{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+this.info.token},body:JSON.stringify({playerId:this.info.playerId}),keepalive:true});}catch{}}
}

export class LocalRoom{
constructor(info,callbacks){this.info=info;this.cb=callbacks;this.host=!!info.host;this.connected=true;this.queue=[];this.peers=[{id:info.playerId,name:info.name}];this.players=new Map([[info.playerId,{id:info.playerId,name:info.name}]]);this.onMessage=e=>this.receive(e.detail);this.timer=null;this.stopped=false;}
start(){window.addEventListener('wildhaven-native-message',this.onMessage);window.addEventListener('wildhaven-native-error',e=>this.cb.status('reconnecting',null,e.detail),{once:true});this.timer=setInterval(()=>this.sync(),400);this.sync();}
action(type,data={}){if(this.queue.length>24||this.stopped)return false;this.queue.push({id:crypto.randomUUID(),type,...data});return true;}
send(data){globalThis.WildhavenLink?.send(JSON.stringify(data));}
sync(){if(this.stopped)return;if(this.host){this.send({kind:'state',sender:this.info.playerId,snapshot:this.cb.snapshot(),players:[...this.players.values()]});this.cb.peers([...this.players.values()]);}else{this.send({kind:'update',sender:this.info.playerId,name:this.info.name,position:this.cb.position(),actions:this.queue.splice(0,8)});}this.cb.status('connected',this.players.size);}
receive(raw){let m;try{m=JSON.parse(raw)}catch{return}if(!m||m.sender===this.info.playerId)return;if(this.host&&m.kind==='update'){this.players.set(m.sender,{id:m.sender,name:m.name||'旅人',position:m.position});for(const e of m.actions||[])this.cb.action({...e,playerId:m.sender,position:m.position});this.peers=[...this.players.values()];}else if(!this.host&&m.kind==='state'){this.info.hostId=m.sender;this.players=new Map((m.players||[]).map(p=>[p.id,p]));this.peers=[...this.players.values()];if(m.snapshot)this.cb.world(m.snapshot);this.cb.peers(this.peers);}}
async leave(){this.stopped=true;clearInterval(this.timer);window.removeEventListener('wildhaven-native-message',this.onMessage);globalThis.WildhavenLink?.stop();}
}
