import * as T from './assets/three.module.min.js';
import {makeHome,updateHomeMesh} from './home-view.js';
import {height,biome,rng,clamp,SHRINES,HOME,BEACON,BUILDS,TAU} from './world.js';
const V=T.Vector3;
const up=new V(0,1,0);
function material(color,extra={}){return new T.MeshStandardMaterial({color,roughness:.88,flatShading:true,...extra});}
export class WorldView{
constructor(canvas,game){this.canvas=canvas;this.game=game;this.angle=0;this.zoom=34;this.targetZoom=34;this.time=0;this.mobile=matchMedia('(pointer:coarse)').matches;this.quality=this.mobile?'balanced':'high';this.scene=new T.Scene();this.scene.background=new T.Color('#8fb5b8');this.scene.fog=new T.FogExp2('#9dbbbb',.0062);this.renderer=new T.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance',alpha:false});this.renderer.setPixelRatio(Math.min(devicePixelRatio,this.mobile?1.25:2));this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=T.PCFSoftShadowMap;this.renderer.outputColorSpace=T.SRGBColorSpace;this.renderer.toneMapping=T.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.2;this.camera=new T.PerspectiveCamera(42,1,.1,600);this.follow=new V(HOME.x,3.5,HOME.z);this.ambient=new T.HemisphereLight(0xc8e5ec,0x52603e,2.2);this.scene.add(this.ambient);this.sun=new T.DirectionalLight(0xffebba,3.0);this.sun.position.set(-35,65,25);this.sun.castShadow=true;this.sun.shadow.mapSize.set(this.quality==='high'?2048:1024,this.quality==='high'?2048:1024);Object.assign(this.sun.shadow.camera,{left:-32,right:32,top:32,bottom:-32,near:1,far:120});this.sun.shadow.bias=-.0005;this.sun.shadow.normalBias=.08;this.sun.shadow.radius=3;this.scene.add(this.sun,this.sun.target);this.effects=[];this.particles=[];this.popups=[];this.shrineMeshes=[];this.enemyMeshes=new Map();this.peers=new Map();this.buildingMeshes=new Map();this.nodeInstances=new Map();this.flames=[];this.grassMaterials=[];this.dummy=new T.Object3D();this.raycaster=new T.Raycaster();this.pointer=new T.Vector2();this.noise=rng(9933);this.makeTextures();this.makeTerrain();this.makeOcean();this.makeNodes();this.makeGroundDetails();this.makeRuins();this.makeAtmosphere();this.player=this.makePlayer();this.scene.add(this.player);this.player.position.set(game.player.x,height(game.player.x,game.player.z),game.player.z);for(const e of game.world.enemies)this.addEnemy(e);for(const b of game.buildings)this.addBuilding(b);this.makeMarker();this.resize();this.syncAll();}
makeTextures(){const c=document.createElement('canvas');c.width=c.height=64;const ctx=c.getContext('2d');const g=ctx.createRadialGradient(32,32,0,32,32,32);g.addColorStop(0,'rgba(255,255,255,1)');g.addColorStop(.12,'rgba(255,255,255,.7)');g.addColorStop(.4,'rgba(255,255,255,.2)');g.addColorStop(1,'rgba(255,255,255,0)');ctx.fillStyle=g;ctx.fillRect(0,0,64,64);this.glowTexture=new T.CanvasTexture(c);}
mesh(geometry,mat,x=0,y=0,z=0,parent=this.scene){const m=new T.Mesh(geometry,mat);m.position.set(x,y,z);m.castShadow=this.quality==='high';m.receiveShadow=true;parent.add(m);return m;}
glow(color,size,parent,x=0,y=0,z=0,opacity=.6){const s=new T.Sprite(new T.SpriteMaterial({map:this.glowTexture,color,transparent:true,opacity,blending:T.AdditiveBlending,depthWrite:false}));s.scale.set(size,size,1);s.position.set(x,y,z);parent.add(s);return s;}
makeTerrain(){const size=270,res=this.mobile?132:190;const geo=new T.PlaneGeometry(size,size,res,res);geo.rotateX(-Math.PI/2);const pos=geo.attributes.position;const colors=new Float32Array(pos.count*3);const c=new T.Color();for(let i=0;i<pos.count;i++){let x=pos.getX(i),z=pos.getZ(i),h=height(x,z);pos.setY(i,h);const b=biome(x,z);if(h<.45)c.set('#c5c9a0');else if(h<1.25)c.set('#cbc9a2');else if(b.id==='frost')c.set('#adbdba');else if(b.id==='amber')c.set('#a6a470');else if(b.id==='forest')c.set('#689881');else c.set('#88ae83');const n=Math.sin(x*.57+z*.43)*Math.cos(z*.61-x*.29);c.multiplyScalar(.94+n*.055);if(Math.abs(x-3*Math.sin(z*.09))<1.7&&z>-6&&z<28)c.lerp(new T.Color('#b8b797'),.5);colors[i*3]=c.r;colors[i*3+1]=c.g;colors[i*3+2]=c.b;}geo.setAttribute('color',new T.BufferAttribute(colors,3));geo.computeVertexNormals();this.terrain=this.mesh(geo,new T.MeshStandardMaterial({vertexColors:true,roughness:1,flatShading:false}));this.terrain.castShadow=false;}
makeOcean(){const detail=this.mobile?32:64,geo=new T.PlaneGeometry(1100,1100,detail,detail);geo.rotateX(-Math.PI/2);this.waterUniforms={uTime:{value:0},uDay:{value:1}};const mat=new T.ShaderMaterial({uniforms:this.waterUniforms,transparent:false,vertexShader:`varying vec3 vPosition; uniform float uTime; void main(){vec3 p=position;p.y+=sin(p.x*.12+uTime*.7)*.12+cos(p.z*.105+uTime*.5)*.12;vPosition=p;gl_Position=projectionMatrix*modelViewMatrix*vec4(p,1.);}`,fragmentShader:`varying vec3 vPosition;uniform float uTime;uniform float uDay;void main(){vec2 p=vPosition.xz;float wave=sin(p.x*.27+p.y*.12+uTime*.65)+sin(p.y*.34-p.x*.05-uTime*.5);float streak=pow(max(0.,sin(p.x*.9+p.y*.32+uTime)*sin(p.y*.8-uTime*.43)),13.);float far=clamp(length(p)/210.,0.,1.);vec3 c=mix(vec3(.17,.50,.52),vec3(.105,.29,.37),far);c+=wave*.012+streak*.10;c*=mix(.31,1.,uDay);gl_FragColor=vec4(c,1.);}`});this.ocean=this.mesh(geo,mat,0,.15,0);this.ocean.castShadow=false;this.ocean.receiveShadow=false;}
instance(geometry,mat,list,transform,colorFn){if(!list.length)return null;const m=new T.InstancedMesh(geometry,mat,list.length);m.castShadow=this.quality==='high';m.receiveShadow=true;for(let i=0;i<list.length;i++){const n=list[i];this.dummy.position.set(n.x,height(n.x,n.z),n.z);this.dummy.rotation.set(0,n.variant*TAU||0,0);this.dummy.scale.setScalar(n.down?0:n.scale||1);transform(this.dummy,n,i);if(n.down)this.dummy.scale.setScalar(0);this.dummy.updateMatrix();m.setMatrixAt(i,this.dummy.matrix);if(colorFn)m.setColorAt(i,new T.Color(colorFn(n,i)));if(n.id!==undefined){if(!this.nodeInstances.has(n.id))this.nodeInstances.set(n.id,[]);this.nodeInstances.get(n.id).push({mesh:m,index:i});}}m.instanceMatrix.needsUpdate=true;m.computeBoundingSphere();this.scene.add(m);return m;}
makeNodes(){const all=this.game.world.nodes,trees=all.filter(n=>n.type==='wood'),pines=trees.filter(n=>n.variant<.52||biome(n.x,n.z).id==='frost'),leaf=trees.filter(n=>!pines.includes(n));const treeColor=n=>{const b=biome(n.x,n.z).id;return b==='frost'?0xa7b7b1:b==='amber'?n.variant>.8?0xc4a45c:0xb5a86b:b==='forest'?0x467d68:0x6e9b70;};this.instance(new T.CylinderGeometry(.18,.31,3.6,6),material(0x706e53),trees,(o,n)=>{o.position.y+=1.8*n.scale;});for(let k=0;k<3;k++)this.instance(new T.ConeGeometry(2.1-k*.4,3.5-k*.35,7),material(0xffffff),pines,(o,n)=>{o.position.y+=(3.1+k*1.55)*n.scale;},n=>{let c=new T.Color(treeColor(n));c.multiplyScalar(1+k*.07);return c;});for(let k=0;k<3;k++)this.instance(new T.IcosahedronGeometry(1,1),material(0xffffff),leaf,(o,n)=>{o.position.x+=Math.sin(k*2.1+n.variant*4)*1.0*n.scale;o.position.z+=Math.cos(k*2.1)*.8*n.scale;o.position.y+=(3.6+k*.55)*n.scale;o.scale.set(1.8*n.scale,1.7*n.scale,1.75*n.scale);},n=>treeColor(n));
const rocks=all.filter(n=>n.type==='stone');this.instance(new T.DodecahedronGeometry(1,0),material(0x8a9da0),rocks,(o,n)=>{o.position.y+=.4;o.scale.set(n.scale*1.3,n.scale*.85,n.scale);o.rotation.z=.2;},n=>biome(n.x,n.z).id==='frost'?0xc1cbc6:0x8a9d96);for(let k=0;k<3;k++)this.instance(new T.OctahedronGeometry(.66,0),material(0x98ecde,{emissive:0x43b6b4,emissiveIntensity:.55,roughness:.25,metalness:.2}),all.filter(n=>n.type==='crystal'),(o,n)=>{o.position.x+=(k-1)*.47;o.position.y+=(k===1?1.15:.7)*n.scale;o.position.z+=Math.sin(k*2)*.22;o.scale.set(n.scale*.75,n.scale*(k===1?2:1.3),n.scale*.75);o.rotation.z=(k-1)*.27;});
const berry=all.filter(n=>n.type==='berry');this.instance(new T.IcosahedronGeometry(.72,1),material(0x5c8b6c),berry,(o,n)=>{o.position.y+=.5;o.scale.set(n.scale,n.scale*.7,n.scale);});for(let k=0;k<4;k++)this.instance(new T.IcosahedronGeometry(.12,1),material(0xdfa579,{emissive:0x8b4933,emissiveIntensity:.15}),berry,(o,n)=>{o.position.y+=.72;o.position.x+=Math.sin(k*1.5+n.variant)*.43;o.position.z+=Math.cos(k*1.5+n.variant)*.43;});}
makeGroundDetails(){const r=rng(617),patches=[],flowers=[],stones=[],count=this.mobile?3200:5600;for(let i=0;i<count;i++){const x=(r()-.5)*202,z=(r()-.5)*202,h=height(x,z);if(h<1.1)continue;if(dist2(x,z,BEACON.x,BEACON.z)<9||SHRINES.some(s=>dist2(x,z,s.x,s.z)<4))continue;const n={x,z,scale:.55+r()*.8,variant:r()};if(i%13===0)flowers.push(n);else if(i%8===0)stones.push(n);else patches.push(n);}
const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute([-.12,0,0,.12,0,0,.02,.5,0,0,0,-.12,0,0,.12,.01,.4,.015],3));g.computeVertexNormals();const grass=material(0xffffff,{side:T.DoubleSide});grass.onBeforeCompile=s=>{s.uniforms.uTime={value:0};s.vertexShader='uniform float uTime;\n'+s.vertexShader;s.vertexShader=s.vertexShader.replace('#include <begin_vertex>','#include <begin_vertex>\n transformed.x += sin(uTime*1.6 + instanceMatrix[3].x*.4 + instanceMatrix[3].z*.3)*position.y*.16;');this.grassMaterials.push(s);};const gm=this.instance(g,grass,patches,()=>{},n=>biome(n.x,n.z).id==='amber'?0xc2b778:biome(n.x,n.z).id==='frost'?0xc1cbb7:0x9cc38b);gm.castShadow=false;const fg=new T.IcosahedronGeometry(.14,0);this.instance(fg,material(0xf5e2b1),flowers,(o,n)=>{o.position.y+=.3;},n=>n.variant>.6?0xc9d5f0:0xeee2b0);this.instance(new T.DodecahedronGeometry(.23,0),material(0xa8b8a5),stones,(o,n)=>{o.position.y+=.05;o.scale.y=.6;});
// Shore rocks give the island a broken, natural silhouette.
const coast=[];for(let i=0;i<155;i++){const a=r()*TAU,d=86+r()*18,x=Math.sin(a)*d,z=Math.cos(a)*d;if(height(x,z)>1)continue;coast.push({x,z,scale:1+r()*2.7,variant:r()});}this.instance(new T.DodecahedronGeometry(1,0),material(0x728e8c),coast,(o,n)=>{o.position.y=Math.max(-.3,o.position.y);o.scale.set(n.scale,n.scale*.85,n.scale*1.1);});}
makeRuins(){const stone=material(0x929e94),dark=material(0x586e68),brass=material(0xc0b788,{metalness:.4,roughness:.5});for(let index=0;index<3;index++){const s=SHRINES[index],g=new T.Group();g.position.set(s.x,height(s.x,s.z),s.z);this.scene.add(g);this.mesh(new T.CylinderGeometry(3.8,4.2,.35,12),stone,0,.05,0,g);this.mesh(new T.CylinderGeometry(2.8,3.4,.28,12),dark,0,.32,0,g);const ring=this.mesh(new T.TorusGeometry(2.5,.035,5,60),brass,0,.49,0,g);ring.rotation.x=Math.PI/2;for(let k=0;k<5;k++){const a=k/5*TAU;this.mesh(new T.BoxGeometry(.65,2.5+k%2,.65),stone,Math.sin(a)*3,1.4,Math.cos(a)*3,g);const cap=this.mesh(new T.BoxGeometry(.9,.24,.9),brass,Math.sin(a)*3,2.72+(k%2)*.5,Math.cos(a)*3,g);cap.rotation.y=a;}
const crystal=this.mesh(new T.OctahedronGeometry(.8,0),material(s.color,{emissive:s.color,emissiveIntensity:.65,roughness:.25,metalness:.2}),0,2.1,0,g);crystal.scale.y=1.7;const glow=this.glow(s.color,5,g,0,2,0,.35);const beam=this.mesh(new T.CylinderGeometry(.12,.5,65,12,1,true),new T.MeshBasicMaterial({color:s.color,transparent:true,opacity:.17,blending:T.AdditiveBlending,depthWrite:false,side:T.DoubleSide}),0,33,0,g);beam.castShadow=false;const halo=this.mesh(new T.TorusGeometry(1.45,.025,5,56),new T.MeshBasicMaterial({color:s.color,transparent:true,opacity:.65}),0,2,0,g);halo.rotation.x=Math.PI/2;this.shrineMeshes.push({group:g,crystal,glow,beam,halo});}
this.beacon=new T.Group();this.beacon.position.set(BEACON.x,height(BEACON.x,BEACON.z),BEACON.z);this.scene.add(this.beacon);this.mesh(new T.CylinderGeometry(7,7.6,.4,12),stone,0,0,0,this.beacon);this.mesh(new T.CylinderGeometry(5.6,6.2,.35,12),dark,0,.35,0,this.beacon);for(let k=0;k<8;k++){const a=k/8*TAU;const g=new T.Group();g.position.set(Math.sin(a)*6.5,0,Math.cos(a)*6.5);g.rotation.y=a;this.beacon.add(g);const h=3.5+(k%3)*.5;this.mesh(new T.BoxGeometry(.85,h,.85),stone,0,h/2,0,g);this.mesh(new T.BoxGeometry(1.12,.25,1.12),brass,0,h,0,g);if(k%2===0)this.mesh(new T.BoxGeometry(3,.36,.8),stone,0,h+.3,0,g);}
const circle=this.mesh(new T.TorusGeometry(4,.05,5,72),new T.MeshBasicMaterial({color:0xd9b9a0,transparent:true,opacity:.45}),0,.6,0,this.beacon);circle.rotation.x=Math.PI/2;this.beaconCrystal=this.mesh(new T.OctahedronGeometry(1.35),material(0xffe3a0,{emissive:0xf4d481,emissiveIntensity:1}),0,4.5,0,this.beacon);this.beaconCrystal.scale.y=2;this.beaconGlow=this.glow(0xffedb2,13,this.beacon,0,5,0,.8);this.beaconBeam=this.mesh(new T.CylinderGeometry(.3,.9,100,12),new T.MeshBasicMaterial({color:0xffedb2,transparent:true,opacity:.15,depthWrite:false,blending:T.AdditiveBlending}),0,50,0,this.beacon);this.beaconBeam.castShadow=false;
// Broken stones and sign posts mark the path out of the camp.
for(let k=0;k<5;k++){const x=3*Math.sin(k*3),z=18-k*5;const m=this.mesh(new T.BoxGeometry(1.8,.12,1.3),material(0xa8b4a0),x,height(x,z)+.06,z);m.rotation.y=k*1.3;}
}
makePlayer(){const g=new T.Group(),ivory=material(0xe5e1c2),green=material(0x3d706b),leather=material(0x755b49),dark=material(0x344844),gold=material(0xe2ca83,{metalness:.45,roughness:.4});this.mesh(new T.CapsuleGeometry(.3,.53,3,7),ivory,0,1,0,g);this.mesh(new T.SphereGeometry(.28,10,8),material(0xd7b88d),0,1.7,.05,g);const hood=this.mesh(new T.SphereGeometry(.34,10,8,0,TAU,0,Math.PI*.78),green,0,1.79,-.03,g);hood.rotation.x=-.22;this.mesh(new T.BoxGeometry(.2,.055,.025),dark,0,1.72,.309,g);this.cape=this.mesh(new T.ConeGeometry(.48,1.03,7,1,true),green,0,1.08,-.09,g);this.cape.scale.z=.65;this.cape.rotation.x=.16;this.mesh(new T.BoxGeometry(.48,.49,.25),leather,0,1.15,-.4,g);this.mesh(new T.BoxGeometry(.51,.08,.29),gold,0,1.15,-.4,g);this.legs=[];for(let s of [-1,1]){let leg=new T.Group();leg.position.set(s*.19,.56,0);g.add(leg);this.mesh(new T.CapsuleGeometry(.105,.3,2,6),dark,0,-.16,0,leg);this.mesh(new T.BoxGeometry(.23,.17,.39),leather,0,-.4,.06,leg);this.legs.push(leg);}
this.swordArm=new T.Group();this.swordArm.name='swordArm';this.swordArm.position.set(-.42,1.25,0);g.add(this.swordArm);this.mesh(new T.CapsuleGeometry(.1,.33,2,6),ivory,0,-.17,0,this.swordArm);this.mesh(new T.SphereGeometry(.1,6,5),material(0xd6b78e),0,-.4,.02,this.swordArm);const sword=new T.Group();sword.name='weapon-sword';sword.position.set(0,-.28,.2);sword.rotation.x=Math.PI/2-.2;this.swordArm.add(sword);this.mesh(new T.BoxGeometry(.09,.9,.05),material(0xd8eeee,{metalness:.65,roughness:.3,emissive:0x86aca9,emissiveIntensity:.1}),0,.43,0,sword);this.mesh(new T.ConeGeometry(.069,.2,4),material(0xd8eeee,{metalness:.65,roughness:.3}),0,.96,0,sword);this.mesh(new T.BoxGeometry(.35,.065,.07),gold,0,-.06,0,sword);this.mesh(new T.CylinderGeometry(.035,.035,.23,6),leather,0,-.19,0,sword);const bow=new T.Group();bow.name='weapon-bow';bow.visible=false;bow.rotation.x=Math.PI/2;bow.position.set(0,.13,.28);this.swordArm.add(bow);this.mesh(new T.TorusGeometry(.46,.028,5,18,Math.PI*1.55),gold,0,.15,0,bow);this.mesh(new T.CylinderGeometry(.012,.012,.93,5),material(0xdff8ed,{emissive:0x7ff0d5,emissiveIntensity:1.2}),0,.15,0,bow);const pistol=new T.Group();pistol.name='weapon-pistol';pistol.visible=false;pistol.position.set(0,.06,.3);pistol.rotation.x=-.2;this.swordArm.add(pistol);this.mesh(new T.BoxGeometry(.18,.25,.72),material(0x78c4c0,{metalness:.5,emissive:0x3cc8be,emissiveIntensity:.8}),0,.08,.32,pistol);this.mesh(new T.BoxGeometry(.13,.38,.16),dark,0,-.21,.04,pistol);const shotgun=new T.Group();shotgun.name='weapon-shotgun';shotgun.visible=false;shotgun.position.set(0,.02,.3);shotgun.rotation.x=-.12;this.swordArm.add(shotgun);this.mesh(new T.BoxGeometry(.26,.22,1.02),material(0xb8a66f,{metalness:.45,emissive:0xd8924d,emissiveIntensity:.45}),0,.04,.46,shotgun);this.mesh(new T.BoxGeometry(.18,.42,.22),leather,0,-.25,.04,shotgun);const axe=new T.Group();axe.visible=false;axe.position.copy(sword.position);axe.rotation.copy(sword.rotation);this.swordArm.add(axe);this.mesh(new T.CylinderGeometry(.045,.05,.85,6),leather,0,.25,0,axe);this.mesh(new T.BoxGeometry(.42,.28,.13),material(0x879399,{roughness:.95}),.14,.6,0,axe);g.userData.weapons={sword,axe,bow,pistol,shotgun};this.mesh(new T.CapsuleGeometry(.1,.4,2,6),green,.4,1.12,0,g);this.mesh(new T.SphereGeometry(.1,6,5),material(0xd6b78e),.42,.81,.04,g);
const marker=this.mesh(new T.RingGeometry(.4,.5,48),new T.MeshBasicMaterial({color:0xe6edbf,side:T.DoubleSide,transparent:true,opacity:.35,depthWrite:false}),0,.04,0,g);marker.rotation.x=-Math.PI/2;marker.castShadow=false;this.playerRing=marker;return g;}
addEnemy(e){const g=new T.Group(),mat=material(e.boss?0x5a6566:0x687a78),trim=material(e.boss?0xdbc29b:0x89b5a5),glowMat=material(e.boss?0xf5ba93:0xeaac91,{emissive:e.boss?0xe79056:0xcb6f60,emissiveIntensity:1.3});let body=this.mesh(new T.DodecahedronGeometry(.65,0),mat,0,.9,0,g);body.scale.set(1,.95,.7);const head=this.mesh(new T.DodecahedronGeometry(.4,0),mat,0,1.62,.02,g);head.scale.set(1,.85,.8);this.mesh(new T.BoxGeometry(.37,.08,.07),glowMat,0,1.64,.34,g);this.mesh(new T.OctahedronGeometry(.22,0),glowMat,0,.97,.46,g);for(let s of [-1,1]){this.mesh(new T.DodecahedronGeometry(.29,0),mat,s*.72,.76,0,g);this.mesh(new T.DodecahedronGeometry(.22,0),trim,s*.7,1.28,-.08,g);const foot=this.mesh(new T.DodecahedronGeometry(.27,0),mat,s*.31,.24,.1,g);foot.scale.set(1,.7,1.3);}if(e.boss){g.scale.setScalar(2.15);for(let k=0;k<3;k++){const c=this.mesh(new T.OctahedronGeometry(.18,0),trim,(k-1)*.3,1.93+Math.sin(k)*.2,0,g);c.scale.y=2;}}
const hp=new T.Group();const bg=this.mesh(new T.PlaneGeometry(1.5,.09),new T.MeshBasicMaterial({color:0x163131,transparent:true,opacity:.7,side:T.DoubleSide}),0,2.4,0,hp);const fill=this.mesh(new T.PlaneGeometry(1.5,.06),new T.MeshBasicMaterial({color:0xe2b69a,side:T.DoubleSide}),0,2.4,.01,hp);hp.visible=false;g.add(hp);this.scene.add(g);this.enemyMeshes.set(e.id,{group:g,body,head,mat,hp,fill});}
makeBuilding(type,ghost=false){const g=new T.Group(),wood=material(0x8b7857),stone=material(0x8e9b91),cloth=material(0xc0bb8e,{side:T.DoubleSide}),gold=material(0xddd3a0);if(type==='fire'){for(let k=0;k<8;k++){const a=k/8*TAU;const m=this.mesh(new T.DodecahedronGeometry(.28,0),stone,Math.sin(a)*.75,.16,Math.cos(a)*.75,g);m.scale.y=.6;}for(let k=0;k<3;k++){const m=this.mesh(new T.CylinderGeometry(.12,.14,1.45,7),wood,0,.2,0,g);m.rotation.z=Math.PI/2;m.rotation.y=k/3*Math.PI;}if(!ghost){const flame=this.mesh(new T.ConeGeometry(.38,1.1,7),material(0xffc478,{emissive:0xff993c,emissiveIntensity:2,transparent:true,opacity:.94}),0,.7,0,g);const core=this.mesh(new T.ConeGeometry(.22,.7,6),material(0xffe7a1,{emissive:0xffd36c,emissiveIntensity:2}),0,.55,0,g);const glow=this.glow(0xffb673,5,g,0,.6,0,.36);this.flames.push({g,flame,core,glow});}}
if(type==='tent'){const geo=new T.BufferGeometry();geo.setAttribute('position',new T.Float32BufferAttribute([-1.7,0,-1.5,0,2.3,-1.5,-1.7,0,1.5,0,2.3,-1.5,0,2.3,1.5,-1.7,0,1.5,1.7,0,-1.5,1.7,0,1.5,0,2.3,-1.5,0,2.3,-1.5,1.7,0,1.5,0,2.3,1.5,-1.7,0,1.5,0,2.3,1.5,1.7,0,1.5],3));geo.computeVertexNormals();this.mesh(geo,cloth,0,0,0,g);for(let z of [-1.65,1.65]){const m=this.mesh(new T.CylinderGeometry(.055,.07,2.7,6),wood,0,1.15,z,g);m.rotation.z=.04;}const ridge=this.mesh(new T.CylinderGeometry(.07,.07,3.6,6),wood,0,2.25,0,g);ridge.rotation.x=Math.PI/2;const door=this.mesh(new T.PlaneGeometry(1.6,1.6),material(0x3c584f,{side:T.DoubleSide}),0,.78,-1.505,g);door.rotation.y=Math.PI;this.mesh(new T.BoxGeometry(2.9,.035,2.8),material(0x89967c),0,.02,0,g);}
if(type==='lamp'){this.mesh(new T.CylinderGeometry(.18,.28,.3,7),stone,0,.15,0,g);this.mesh(new T.CylinderGeometry(.045,.06,1.65,6),wood,0,.98,0,g);this.mesh(new T.OctahedronGeometry(.3),material(0xbef4d3,{emissive:0x7be6c9,emissiveIntensity:1.2}),0,2.04,0,g);this.mesh(new T.ConeGeometry(.42,.25,6),gold,0,2.47,0,g);if(!ghost)this.glow(0xa7edcf,4,g,0,2,0,.5);}
if(type==='workbench'){this.mesh(new T.BoxGeometry(2.2,.18,.9),wood,0,1.15,0,g);for(const x of [-.88,.88])for(const z of [-.28,.28])this.mesh(new T.BoxGeometry(.14,1.2,.14),wood,x,.58,z,g);this.mesh(new T.BoxGeometry(.62,.12,.5),stone,.38,1.36,0,g);this.mesh(new T.CylinderGeometry(.08,.08,1.1,6),gold,-.55,1.65,0,g);}
if(type==='fence'){for(let x of [-1.2,1.2]){this.mesh(new T.BoxGeometry(.16,1.3,.16),wood,x,.65,0,g);this.mesh(new T.ConeGeometry(.13,.2,4),gold,x,1.37,0,g);}for(let y of [.45,1])this.mesh(new T.BoxGeometry(2.6,.13,.12),wood,0,y,0,g);}
if(type==='sailcart'){for(const x of [-.88,.88])for(const z of [-.62,.62]){const w=this.mesh(new T.CylinderGeometry(.35,.35,.16,10),stone,x,.38,z,g);w.rotation.z=Math.PI/2;}this.mesh(new T.BoxGeometry(2.1,.22,1.35),wood,0,.7,0,g);this.mesh(new T.BoxGeometry(1.2,.18,.72),cloth,0,.95,.1,g);const mast=this.mesh(new T.CylinderGeometry(.055,.07,2.65,7),wood,0,1.98,0,g);const sail=this.mesh(new T.PlaneGeometry(1.5,1.65),cloth,.75,2.25,0,g);sail.name='sail';sail.rotation.y=Math.PI/2;g.userData.sail=sail;g.userData.sailSpeed=0;mast.castShadow=true;}
makeHome(this,g,type,ghost);if(ghost){g.traverse(o=>{if(o.isMesh){o.material=o.material.clone();o.material.transparent=true;o.material.opacity=.5;o.material.depthWrite=false;o.castShadow=false;}});}return g;}
addBuilding(b){let g=this.buildingMeshes.get(b.id);if(!g){g=this.makeBuilding(b.type);this.scene.add(g);this.buildingMeshes.set(b.id,g);}g.position.set(b.x,height(b.x,b.z),b.z);g.rotation.y=b.angle;updateHomeMesh(g,b,this.game.player);}
removeBuilding(id){const g=this.buildingMeshes.get(id);if(!g)return;this.scene.remove(g);g.traverse(o=>{if(o.geometry)o.geometry.dispose();if(o.material)o.material.dispose();});this.buildingMeshes.delete(id);}
makeAtmosphere(){const r=rng(2514),count=120,p=new Float32Array(count*3);this.motes=[];for(let i=0;i<count;i++){const x=(r()-.5)*190,z=(r()-.5)*190,y=Math.max(1,height(x,z))+r()*7;this.motes.push({x,y,z,phase:r()*TAU});p[i*3]=x;p[i*3+1]=y;p[i*3+2]=z;}const geo=new T.BufferGeometry();geo.setAttribute('position',new T.BufferAttribute(p,3));this.moteCloud=new T.Points(geo,new T.PointsMaterial({color:0xf5e6a5,size:.12,map:this.glowTexture,transparent:true,opacity:.85,blending:T.AdditiveBlending,depthWrite:false}));this.scene.add(this.moteCloud);const stars=new Float32Array(450*3);for(let i=0;i<450;i++){const a=r()*TAU,el=.3+r()*1.2;stars[i*3]=Math.cos(a)*Math.cos(el)*220;stars[i*3+1]=Math.sin(el)*220;stars[i*3+2]=Math.sin(a)*Math.cos(el)*220;}const sg=new T.BufferGeometry();sg.setAttribute('position',new T.BufferAttribute(stars,3));this.stars=new T.Points(sg,new T.PointsMaterial({size:.6,color:0xd8eeee,transparent:true,opacity:0,sizeAttenuation:true}));this.scene.add(this.stars);this.birds=[];const birdMat=new T.MeshBasicMaterial({color:0x365955,side:T.DoubleSide});for(let i=0;i<8;i++){const g=new T.Group();const wingGeo=new T.BufferGeometry();wingGeo.setAttribute('position',new T.Float32BufferAttribute([0,0,0,1.2,0,.3,.4,0,-.28],3));const left=new T.Mesh(wingGeo,birdMat),right=new T.Mesh(wingGeo,birdMat);right.scale.x=-1;g.add(left,right);this.scene.add(g);this.birds.push({g,left,right,phase:r()*TAU,radius:22+r()*35,y:19+r()*8});}}
makeMarker(){this.marker=new T.Group();const ring=new T.Mesh(new T.RingGeometry(.35,.43,40),new T.MeshBasicMaterial({color:0xf4e8b9,side:T.DoubleSide,transparent:true,opacity:.8,depthWrite:false}));ring.rotation.x=-Math.PI/2;this.marker.add(ring);this.scene.add(this.marker);this.marker.visible=false;this.markerLife=0;const ring2=new T.Mesh(new T.RingGeometry(.9,1.0,40),new T.MeshBasicMaterial({color:0xdbe9b9,side:T.DoubleSide,transparent:true,opacity:.6,depthWrite:false}));ring2.rotation.x=-Math.PI/2;this.selection=ring2;this.scene.add(ring2);this.selection.visible=false;this.aimRing=new T.Mesh(new T.RingGeometry(.72,.86,48),new T.MeshBasicMaterial({color:0x9ef9e5,side:T.DoubleSide,transparent:true,opacity:0,depthWrite:false,blending:T.AdditiveBlending}));this.aimRing.rotation.x=-Math.PI/2;this.scene.add(this.aimRing);this.aimRing.visible=false;this.aimGlow=this.glow(0x9cf3df,0,this.scene,0,-20,0,0);this.aimGlow.visible=false;this.aimBeam=new T.Mesh(new T.CylinderGeometry(.028,.1,1,8,1,true),new T.MeshBasicMaterial({color:0x9dffe7,transparent:true,opacity:.72,depthWrite:false,blending:T.AdditiveBlending}));this.scene.add(this.aimBeam);this.aimBeam.visible=false;}
showTarget(x,z){this.marker.position.set(x,height(x,z)+.11,z);this.marker.visible=true;this.markerLife=1.3;}

updatePeers(players,selfId){const ids=new Set();for(const peer of players){if(peer.id===selfId)continue;ids.add(peer.id);let p=this.peers.get(peer.id);if(!p){const g=this.player.clone(true);const palette=[0xb7a4cc,0xc2a068,0x80a5bc,0xc68e7c];let ci=0;for(const c of peer.id)ci+=c.charCodeAt(0);g.traverse(o=>{if(o.isMesh){o.material=o.material.clone();if(o.material.color&&o.material.color.getHex()===0x3d706b)o.material.color.setHex(palette[ci%4]);}});const c=document.createElement('canvas');c.width=256;c.height=64;const ctx=c.getContext('2d');ctx.fillStyle='rgba(18,46,47,.8)';ctx.beginPath();ctx.roundRect(10,8,236,48,10);ctx.fill();ctx.font='24px sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillStyle='#e8e9c9';ctx.fillText(peer.name.slice(0,12),128,33,218);const tex=new T.CanvasTexture(c);const label=new T.Sprite(new T.SpriteMaterial({map:tex,transparent:true,depthTest:false}));label.position.set(0,2.8,0);label.scale.set(3.4,.85,1);g.add(label);this.scene.add(g);g.position.set(peer.position.x,height(peer.position.x,peer.position.z),peer.position.z);p={group:g,data:peer.position};this.peers.set(peer.id,p);}p.data=peer.position;}for(const [id,p]of this.peers){if(!ids.has(id)){this.scene.remove(p.group);p.group.traverse(o=>{if(o.material)o.material.dispose();});this.peers.delete(id);}}}

setGhost(type){if(this.ghost){this.scene.remove(this.ghost);this.disposeGroup(this.ghost);this.ghost=null;}if(type){this.ghost=this.makeBuilding(type,true);this.scene.add(this.ghost);}}
updateGhost(x,z,angle,valid){if(!this.ghost)return;this.ghost.position.set(x,height(x,z)+.03,z);this.ghost.rotation.y=angle;this.ghost.traverse(o=>{if(o.isMesh)o.material.color.set(valid?0xb6e7b8:0xe6a08c);});}
disposeGroup(group){group.traverse(o=>{if(o.geometry)o.geometry.dispose();if(o.material){if(Array.isArray(o.material))o.material.forEach(m=>m.dispose());else o.material.dispose();}});}
nodeDown(id){const data=this.nodeInstances.get(id)||[];this.dummy.position.set(0,-30,0);this.dummy.scale.setScalar(0);this.dummy.updateMatrix();for(const {mesh,index}of data){mesh.setMatrixAt(index,this.dummy.matrix);mesh.instanceMatrix.needsUpdate=true;}}
syncAll(){for(let i=0;i<3;i++)this.shrineMeshes[i].beam.visible=this.game.shrines[i];this.beaconCrystal.visible=this.game.won;this.beaconGlow.visible=this.game.won;this.beaconBeam.visible=this.game.won;for(const e of this.game.world.enemies){const m=this.enemyMeshes.get(e.id);m.group.visible=!e.dead;}}
setQuality(q){this.quality=q;const cap=q==='high'?(this.mobile?1.5:2):q==='balanced'?1.25:1;this.renderer.setPixelRatio(Math.min(devicePixelRatio,cap));this.renderer.shadowMap.enabled=q!=='low';this.sun.shadow.mapSize.set(q==='high'?2048:1024,q==='high'?2048:1024);if(this.sun.shadow.map){this.sun.shadow.map.dispose();this.sun.shadow.map=null;}this.resize();}
resize(){const w=innerWidth,h=innerHeight;this.renderer.setSize(w,h,false);this.camera.aspect=w/h;this.camera.updateProjectionMatrix();}
worldPoint(clientX,clientY){this.pointer.set(clientX/innerWidth*2-1,-clientY/innerHeight*2+1);this.raycaster.setFromCamera(this.pointer,this.camera);const hits=this.raycaster.intersectObject(this.terrain,false);return hits[0]?.point;}
burst(x,z,color,count=12,y=null){for(let i=0;i<count;i++){const m=new T.Mesh(new T.IcosahedronGeometry(.07+Math.random()*.07,0),new T.MeshBasicMaterial({color,transparent:true,opacity:1}));const a=Math.random()*TAU,s=.7+Math.random()*2.8;m.position.set(x,y??height(x,z)+.8,z);this.scene.add(m);this.particles.push({mesh:m,vx:Math.sin(a)*s,vy:1.3+Math.random()*3,vz:Math.cos(a)*s,life:.4+Math.random()*.6,max:1});}}
ring(x,z,color,r=2.8,life=.5){const m=new T.Mesh(new T.RingGeometry(r-.09,r,64),new T.MeshBasicMaterial({color,transparent:true,opacity:.75,side:T.DoubleSide,depthWrite:false}));m.rotation.x=-Math.PI/2;m.position.set(x,height(x,z)+.13,z);this.scene.add(m);this.effects.push({mesh:m,life,max:life,kind:'ring'});}
handle(e){const p=this.game.player;if(e.type==='node-down')this.nodeDown(e.id);if(e.type==='gather'){this.burst(e.x,e.z,e.type==='wood'?0xcad29c:e.type==='crystal'?0xa3f0df:e.type==='berry'?0xf2b18b:0xb4c5bd,9);}
if(e.type==='swing'){const mat=new T.MeshBasicMaterial({color:e.combo===0?0xffdea4:0xd9efe0,transparent:true,opacity:.75,side:T.DoubleSide,depthWrite:false});const mesh=new T.Mesh(new T.RingGeometry(1.15,2.6,32,1,0,Math.PI*1.15),mat);mesh.rotation.x=-Math.PI/2;mesh.rotation.z=-e.angle-.1;mesh.position.set(e.x,height(e.x,e.z)+1,e.z);this.scene.add(mesh);this.effects.push({mesh,life:.2,max:.2,kind:'slash'});}
if(e.type==='hit'){this.burst(e.x,e.z,0xffdcb0,11);this.shake=.06;}if(e.type==='aurora-aim'){this.ring(e.x,e.z,0x93f4e5,Math.min(5,e.range*.18),.35);if(e.target)this.ring(e.target.x,e.target.z,0xd9fff5,1.15,.42);}if(e.type==='projectile'){this.ring(e.x+Math.sin(e.angle)*Math.min(7,e.range*.35),e.z+Math.cos(e.angle)*Math.min(7,e.range*.35),0x9ef3df,1.1,.28);}if(e.type==='defeat')this.burst(e.x,e.z,e.boss?0xffe5a1:0xb2c5b2,e.boss?65:20);if(e.type==='damage'){this.shake=.25;this.burst(p.x,p.z,0xe8a489,8);}if(e.type==='dash'){this.ring(p.x,p.z,0xe4eccd,1.1,.4);this.burst(p.x,p.z,0xd3e9c5,7,.5+height(p.x,p.z));}if(e.type==='windup')this.ring(e.x,e.z,0xeab087,e.boss?6:2.8,e.boss?.85:.42);if(e.type==='enemy-attack'){this.ring(e.x,e.z,0xeac4a0,e.boss?6.7:2.9,.3);if(e.boss)this.shake=.13;}if(e.type==='shrine'){this.burst(SHRINES[e.index].x,SHRINES[e.index].z,SHRINES[e.index].color,45);this.syncAll();}if(e.type==='victory'){this.syncAll();this.burst(BEACON.x,BEACON.z,0xffeeb6,100,8);}if(e.type==='build'){this.addBuilding(e.building);this.burst(e.building.x,e.building.z,0xd2dfb2,15);}if(e.type==='recycle'){this.removeBuilding(e.id);this.burst(e.x,e.z,0xd2dfb2,11);}if(e.type==='vehicle'){const g=this.buildingMeshes.get(e.building.id);if(g){const previous=g.userData.heading??e.building.angle;g.userData.sailTurn=Math.atan2(Math.sin(e.building.angle-previous),Math.cos(e.building.angle-previous));g.userData.heading=e.building.angle;g.position.set(e.building.x,height(e.building.x,e.building.z),e.building.z);g.rotation.y=e.building.angle;g.userData.sailSpeed=e.speed||0;}}if(e.type==='burst')this.burst(e.x,e.z,e.color,e.count);if(['heal','rest','repair'].includes(e.type)){this.burst(e.x??p.x,e.z??p.z,0xd7efb9,20);this.ring(e.x??p.x,e.z??p.z,0xd6e7b1,2,.7);}if(e.type==='respawn'){this.follow.set(p.x,height(p.x,p.z),p.z);}}
update(dt,playing=true){this.time+=dt;const t=this.time,p=this.game.player;this.waterUniforms.uTime.value=t;for(const s of this.grassMaterials)s.uniforms.uTime.value=t;const hour=(this.game.clock%720)/720*24;const day=clamp(Math.sin((hour-6)/24*TAU)*1.6+.3,0,1);this.waterUniforms.uDay.value=day;const dusk=clamp(1-Math.abs(hour-18)/2,0,1)*.55;this.ambient.intensity=.55+day*1.65;this.sun.intensity=.3+day*2.7;this.sun.color.set(0xffebba).lerp(new T.Color(0xffb88a),dusk);const sky=new T.Color(0x243947).lerp(new T.Color(0xa2bec0),day).lerp(new T.Color(0xc3afa3),dusk);this.scene.background.copy(sky);this.scene.fog.color.copy(sky);this.stars.material.opacity=(1-day)*.8;this.renderer.toneMappingExposure=1.04+day*.16;
this.player.position.set(p.x,height(p.x,p.z)+(p.moving?Math.sin(t*15)*.055:0),p.z);let delta=Math.atan2(Math.sin(p.angle-this.player.rotation.y),Math.cos(p.angle-this.player.rotation.y));this.player.rotation.y+=delta*Math.min(1,dt*18);this.player.visible=!(p.invulnerable>0&&Math.floor(t*14)%2===0);for(const [name,weapon]of Object.entries(this.player.userData.weapons||{}))weapon.visible=name===(p.equipped||'sword');this.cape.rotation.x=.12+Math.sin(t*4)*.05+p.moving*.18;this.legs[0].rotation.x=p.moving?Math.sin(t*12)*.7:Math.sin(t*2)*.025;this.legs[1].rotation.x=-this.legs[0].rotation.x;const ranged=['bow','pistol','shotgun'].includes(p.equipped);this.swordArm.rotation.z=p.attack>0?(ranged?-.72:-1.2-Math.sin(p.attack/.3*Math.PI)*1.3):-.1;this.swordArm.rotation.x=p.attack>0?(ranged?-.62:-Math.sin(p.attack/.3*Math.PI)*1.3):Math.sin(t*2)*.04;const aimRange={bow:24,pistol:19,shotgun:10}[p.equipped];if(aimRange){const ax=p.x+Math.sin(p.angle)*aimRange,az=p.z+Math.cos(p.angle)*aimRange,from=new V(p.x,height(p.x,p.z)+1.08,p.z),to=new V(ax,height(ax,az)+.55,az),beam=to.clone().sub(from),beamLength=beam.length();this.aimRing.visible=false;this.aimGlow.visible=false;this.aimBeam.visible=true;this.aimBeam.position.copy(from).add(to).multiplyScalar(.5);this.aimBeam.scale.set(1,beamLength,1);this.aimBeam.quaternion.setFromUnitVectors(up,beam.normalize());this.aimBeam.material.opacity=.42+Math.sin(t*10)*.16;}else{this.aimRing.visible=false;this.aimGlow.visible=false;this.aimBeam.visible=false;}
for(let i=0;i<3;i++){const m=this.shrineMeshes[i],lit=this.game.shrines[i];m.crystal.rotation.y=t*.55+i;m.crystal.position.y=2.2+Math.sin(t*1.4+i)*.18;m.glow.material.opacity=(lit?.55:.23)+Math.sin(t*2+i)*.06;m.halo.rotation.z=t*.3;m.halo.material.opacity=lit?.85:.28;m.beam.visible=lit;}
if(this.game.won){this.beaconCrystal.rotation.y=t*.5;this.beaconCrystal.position.y=4.5+Math.sin(t)*.4;}
for(const e of this.game.world.enemies){const m=this.enemyMeshes.get(e.id);if(!m)continue;const visible=!e.dead&&dist2(e.x,e.z,p.x,p.z)<88;m.group.visible=visible;if(!visible)continue;const asleep=e.boss&&!this.game.shrines.every(Boolean);m.group.position.lerp(new V(e.x,height(e.x,e.z)+(asleep?-.15:Math.sin(t*3+e.id)*.06),e.z),this.game.isGuest?Math.min(1,dt*13):1);m.group.rotation.y=e.angle;m.body.rotation.z=e.windup>0?Math.sin(t*35)*.07:0;m.mat.emissive.set(e.hitFlash>0?0xffd0a0:0x000000);m.mat.emissiveIntensity=e.hitFlash>0?.5:0;m.hp.visible=!asleep&&e.hp<e.maxHp;m.hp.quaternion.copy(m.group.quaternion).invert().multiply(this.camera.quaternion);m.fill.scale.x=Math.max(0,e.hp/e.maxHp);m.fill.position.x=-(1-e.hp/e.maxHp)*.75;}
for(const f of this.flames){if(dist2(f.flame.parent.position.x,f.flame.parent.position.z,p.x,p.z)>70)continue;f.flame.scale.set(1+Math.sin(t*14)*.1,1+Math.sin(t*11)*.15,1);f.core.scale.y=1+Math.sin(t*17)*.18;f.glow.material.opacity=.3+Math.sin(t*8)*.05;}for(const g of this.buildingMeshes.values()){g.visible=dist2(g.position.x,g.position.z,p.x,p.z)<96;if(!g.visible)continue;const sail=g.userData.sail;if(!sail)continue;const wind=.1+(g.userData.sailSpeed||0)*.14;g.userData.sailTurn=(g.userData.sailTurn||0)*Math.exp(-dt*5);sail.rotation.y=Math.PI/2+g.userData.sailTurn*.55;sail.rotation.z=Math.sin(t*(3+(g.userData.sailSpeed||0)*2)+g.position.x*.12)*wind;sail.scale.x=1+Math.sin(t*5+g.position.z)*wind*.08;}
const mp=this.moteCloud.geometry.attributes.position;for(let i=0;i<this.motes.length;i++){const n=this.motes[i];mp.setXYZ(i,n.x+Math.sin(t*.15+n.phase)*1.5,n.y+Math.sin(t*.6+n.phase)*.3,n.z+Math.cos(t*.16+n.phase)*1.2);}mp.needsUpdate=true;this.moteCloud.material.opacity=.35+(1-day)*.55;for(const b of this.birds){const a=t*.045+b.phase;b.g.position.set(Math.sin(a)*b.radius,b.y,Math.cos(a)*b.radius);b.g.rotation.y=-a;b.left.rotation.z=Math.sin(t*4+b.phase)*.36;b.right.rotation.z=-b.left.rotation.z;}
for(let i=this.particles.length-1;i>=0;i--){const v=this.particles[i];v.life-=dt;v.vy-=dt*7;v.mesh.position.x+=v.vx*dt;v.mesh.position.y+=v.vy*dt;v.mesh.position.z+=v.vz*dt;v.mesh.material.opacity=Math.max(0,v.life);if(v.life<=0){this.scene.remove(v.mesh);this.disposeGroup(v.mesh);this.particles.splice(i,1);}}
for(let i=this.effects.length-1;i>=0;i--){const v=this.effects[i];v.life-=dt;v.mesh.material.opacity=Math.max(0,v.life/v.max)*.7;if(v.kind==='ring')v.mesh.scale.setScalar(1+(1-v.life/v.max)*.22);if(v.kind==='slash')v.mesh.rotation.z+=dt*6;if(v.life<=0){this.scene.remove(v.mesh);this.disposeGroup(v.mesh);this.effects.splice(i,1);}}
for(const peer of this.peers.values()){const r=peer.data,v=peer.group;v.position.lerp(new V(r.x,height(r.x,r.z)+(r.moving?Math.sin(t*15)*.05:0),r.z),1-Math.exp(-dt*12));const da=Math.atan2(Math.sin(r.angle-v.rotation.y),Math.cos(r.angle-v.rotation.y));v.rotation.y+=da*Math.min(1,dt*12);const arm=v.getObjectByName('swordArm');if(arm)arm.rotation.z=r.attack>0?-2.1:-.1;}
if(this.markerLife>0){this.markerLife-=dt;this.marker.scale.setScalar(1+Math.sin(t*6)*.15);this.marker.visible=true;}else this.marker.visible=false;const near=playing?this.game.nearest():null;if(near){this.selection.visible=true;this.selection.position.set(near.target.x,height(near.target.x,near.target.z)+.13,near.target.z);this.selection.material.opacity=.35+Math.sin(t*4)*.15;this.selection.scale.setScalar(near.kind==='shrine'?3:1);}else this.selection.visible=false;
this.zoom+=(this.targetZoom-this.zoom)*Math.min(1,dt*5);const desired=new V(p.x,height(p.x,p.z)+.9,p.z);this.follow.lerp(desired,1-Math.exp(-dt*6));const angle=this.angle+(playing?0:Math.sin(t*.07)*.12);const target=new V(this.follow.x+Math.sin(angle)*this.zoom,this.follow.y+this.zoom*.94,this.follow.z+Math.cos(angle)*this.zoom);if(this.shake>0){this.shake=Math.max(0,this.shake-dt);target.x+=(Math.random()-.5)*this.shake*2;target.y+=(Math.random()-.5)*this.shake;}this.camera.position.copy(target);this.camera.lookAt(this.follow);this.sun.position.set(this.follow.x-30,this.follow.y+65,this.follow.z+25);this.sun.target.position.copy(this.follow);this.sun.target.updateMatrixWorld();this.renderer.render(this.scene,this.camera);}
}
function dist2(x,z,a,b){return Math.hypot(x-a,z-b);}
