import assert from 'node:assert/strict';
import {Game,BUILDS} from '../public/world.js';
const g=new Game();g.world.nodes=[];g.buildings=[];g.player.x=30;g.player.z=30;g.inventory={wood:999,stone:999,crystal:999,berry:999};
assert.equal(g.build('wall',30,31.5),false,'walls require a floor');
assert.equal(g.build('floor',30,30),true);
assert.equal(g.build('floor',30,30),false,'no duplicate floors');
for(const [type,x,z,a] of [['door',30,31.5,0],['wall',30,28.5,0],['wall',31.5,30,Math.PI/2],['wall',28.5,30,Math.PI/2],['roof',30,30,0]])assert.equal(g.build(type,x,z,a),true,`${type} can attach`);
assert.equal(g.homeScore().rooms,1);
const floor=g.buildings.find(b=>b.type==='floor'),door=g.buildings.find(b=>b.type==='door');
assert.equal(g.buildingAction(floor.id,'recycle'),false,'cannot remove support');
assert.equal(g.buildingAction(floor.id,'upgrade'),true);assert.equal(floor.level,2);
const restored=new Game('adventure',JSON.parse(JSON.stringify(g.snapshot())));
assert.equal(restored.buildings.find(b=>b.id===floor.id).maxDurability,BUILDS.floor.maxDurability*2);
g.player.x=30;g.player.z=32.1;g.moveEntity(g.player,0,-.2);assert.equal(g.player.z,32.1,'closed door blocks');
assert.equal(g.buildingAction(door.id,'door'),true);g.moveEntity(g.player,0,-.2);assert(g.player.z<32.1,'open door allows passage');
assert.equal(g.buildingAction(door.id,'door'),false,'do not close on players');
g.player.x=30;g.player.z=30;
assert.equal(g.build('chest',30,30),true);
const chest=g.buildings.find(b=>b.type==='chest'),total=g.inventory.wood;
assert.equal(g.buildingAction(chest.id,'store','wood',10),true);
assert.equal(g.inventory.wood+chest.storage.wood,total);
assert.equal(g.buildingAction(chest.id,'recycle'),false,'nonempty chest protected');
assert.equal(g.buildingAction(chest.id,'store','wood',200),false,'capacity enforced');
assert.equal(g.buildingAction(chest.id,'take','wood',-2),false,'reject negative transfer');
g.player.id='visitor';assert.equal(g.buildingAction(chest.id,'take','wood',1),false,'owner permission enforced');
g.player.id=null;assert.equal(g.buildingAction(chest.id,'take','wood',10),true);assert.equal(g.inventory.wood,total);
assert.equal(g.buildingAction(chest.id,'recycle'),true);
for(const b of [...g.buildings].filter(b=>b.type!=='floor'))assert.equal(g.buildingAction(b.id,'recycle'),true);
assert.equal(g.buildingAction(floor.id,'recycle'),true);assert.equal(g.buildings.length,0);
console.log('Home placement, enclosure, collision, upgrade/save, permissions, storage and recycling passed');
