plugins {
  id 'com.android.application'
}

android {
  namespace 'co.abeto.wildhaven'
  compileSdk 35

  defaultConfig {
    applicationId 'co.abeto.wildhaven.homepreview'
    minSdk 24
    targetSdk 35
    versionCode 10
    versionName '1.4.0-home'
  }
}

dependencies {
  implementation 'androidx.webkit:webkit:1.12.1'
}
